Ejemplos Numpy

In [3]:
#Hacer una matriz de números aleatorios de 10 x 10 
import numpy as np
matrizrandom1 = np.random.rand(10,10)
print(matrizrandom1)

[[0.61964107 0.58957146 0.31044074 0.52130266 0.03608812 0.73572963
  0.30833868 0.42720079 0.37798599 0.43883011]
 [0.11106199 0.67759095 0.28323588 0.04071984 0.65483052 0.93978071
  0.81233755 0.00759806 0.11211271 0.62430523]
 [0.89799577 0.28303214 0.52718618 0.65258786 0.4611897  0.94085999
  0.19717359 0.6315939  0.69858354 0.53868286]
 [0.08858919 0.17072149 0.35693007 0.40849959 0.16821022 0.62040039
  0.27878941 0.35398319 0.67660644 0.9520575 ]
 [0.13769136 0.7239964  0.14422353 0.47683728 0.51061293 0.7264284
  0.07448987 0.50398368 0.21850759 0.14234688]
 [0.19833648 0.76203406 0.80602616 0.75630562 0.82278849 0.37509021
  0.521392   0.07297858 0.17841739 0.26807133]
 [0.94458889 0.43836053 0.23161836 0.03978866 0.51950512 0.28019322
  0.60991252 0.94861994 0.50001695 0.43901295]
 [0.57189152 0.00536537 0.32654532 0.72978868 0.11050795 0.62254505
  0.27380776 0.72568109 0.29097629 0.72421081]
 [0.83603753 0.34617071 0.1218364  0.55534316 0.47179893 0.41317932
  0.15743323 

In [5]:
#Generar una matriz booleana con los valores mayores a .5
matrizbooleana1 = (matrizrandom1 > .5)
print(matrizbooleana1)

[[ True  True False  True False  True False False False False]
 [False  True False False  True  True  True False False  True]
 [ True False  True  True False  True False  True  True  True]
 [False False False False False  True False False  True  True]
 [False  True False False  True  True False  True False False]
 [False  True  True  True  True False  True False False False]
 [ True False False False  True False  True  True  True False]
 [ True False False  True False  True False  True False  True]
 [ True False False  True False False False False False False]
 [False  True False  True  True  True  True False False False]]


In [7]:
#Posteriormente convertir la matriz booleana a binaria y multiplicar los valores por la matriz
#inicial para que queden sólo los valores mayores a .5
filtro1 = np.array(matrizbooleana1, dtype = np.int32)
print(filtro1)
resultado1 = matrizrandom1 * filtro1
print(resultado1)


[[1 1 0 1 0 1 0 0 0 0]
 [0 1 0 0 1 1 1 0 0 1]
 [1 0 1 1 0 1 0 1 1 1]
 [0 0 0 0 0 1 0 0 1 1]
 [0 1 0 0 1 1 0 1 0 0]
 [0 1 1 1 1 0 1 0 0 0]
 [1 0 0 0 1 0 1 1 1 0]
 [1 0 0 1 0 1 0 1 0 1]
 [1 0 0 1 0 0 0 0 0 0]
 [0 1 0 1 1 1 1 0 0 0]]
[[0.61964107 0.58957146 0.         0.52130266 0.         0.73572963
  0.         0.         0.         0.        ]
 [0.         0.67759095 0.         0.         0.65483052 0.93978071
  0.81233755 0.         0.         0.62430523]
 [0.89799577 0.         0.52718618 0.65258786 0.         0.94085999
  0.         0.6315939  0.69858354 0.53868286]
 [0.         0.         0.         0.         0.         0.62040039
  0.         0.         0.67660644 0.9520575 ]
 [0.         0.7239964  0.         0.         0.51061293 0.7264284
  0.         0.50398368 0.         0.        ]
 [0.         0.76203406 0.80602616 0.75630562 0.82278849 0.
  0.521392   0.         0.         0.        ]
 [0.94458889 0.         0.         0.         0.51950512 0.
  0.60991252 0.94861994 0.50

In [10]:
matrizrandom1[matrizbooleana1]


array([0.61964107, 0.58957146, 0.52130266, 0.73572963, 0.67759095,
       0.65483052, 0.93978071, 0.81233755, 0.62430523, 0.89799577,
       0.52718618, 0.65258786, 0.94085999, 0.6315939 , 0.69858354,
       0.53868286, 0.62040039, 0.67660644, 0.9520575 , 0.7239964 ,
       0.51061293, 0.7264284 , 0.50398368, 0.76203406, 0.80602616,
       0.75630562, 0.82278849, 0.521392  , 0.94458889, 0.51950512,
       0.60991252, 0.94861994, 0.50001695, 0.57189152, 0.72978868,
       0.62254505, 0.72568109, 0.72421081, 0.83603753, 0.55534316,
       0.50608471, 0.8254959 , 0.75588935, 0.50282504, 0.54910135])

Ejemplo 2
Producto punto

In [14]:
matrizA = np.array([[2,5],[4,10]])
matrizB = np.array([[3,6],[6,12]])
print(matrizA)
print(matrizB)


[[ 2  5]
 [ 4 10]]
[[ 3  6]
 [ 6 12]]


In [16]:
resultado = np.dot(matrizA, matrizB)
print(resultado)


[[ 36  72]
 [ 72 144]]


Ejemplo 3 Función semiverseno

In [ ]:
#Ver formula de semiverseno en pyhton vs numpy
#from math import radians, cos, sin, asin, sqrt

#def ObtenerDistancia(lat1, lon1, lat2, lon2):
    # Convertimos grados a radianes
    #lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # Formula del semiverseno:
    #dlon = lon2 - lon1 
    #dlat = lat2 - lat1 
    #a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    #c = 2 * asin(sqrt(a)) 
    #r = 6371 
    #return c * r
    
    